### ADD STUDENT
POST http://localhost:4004/odata/v4/z-service-students/addStudent
Content-Type: application/json

{
  "student": {
    "studentID": "S1004",
    "firstName": "ABC",
    "lastName": "DEF",
    "class": "10",
    "section": "B",

    "email": "test@gmail.com",
    "phoneNumber": "9876543210",
    "emergencyContactName": "Mother",
    "guardianName": "Raj Sharma",
    "address": "New Delhi",

    "dateOfBirth": "2017-05-10",
    "enrollmentDate": "2020-06-15"
  }
}


### DELETE STUDENT
POST http://localhost:4004/odata/v4/z-service-students/deleteStudent
Content-Type: application/json

{
  "student": {
    "studentID": "S1002"
  }
}



### UPDATE STUDENT
POST http://localhost:4004/odata/v4/z-service-students/updateStudent
Content-Type: application/json

{
  "student": {
    "studentID": "S1001",
    "firstName": "Chitrasen",
    "lastName": "Doe",
    "class": "10",
    "section": "A",
    "email": "john@example.com",
    "phoneNumber": "9999999999",
    "emergencyContactName": "Parent",
    "guardianName": "Father",
    "address": "Delhi",
    "dateOfBirth": "2005-01-01",
    "enrollmentDate": "2020-06-01"
  }
}
